# Generated by Django 3.1.4 on 2021-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email поле')),
                ('username', models.CharField(max_length=150, verbose_name='Імя користувача')),
                ('is_editor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
