# Generated by Django 3.1.4 on 2021-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='main.Lesson'),
        ),
    ]
